  # This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates SecurityCodeScan with GitHub's Code Scanning feature
# SecurityCodeScan is a vulnerability patterns detector for C# and VB.NET

name: DotNetBuild_With_MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  DotNet_MSBuild:
    uses: jpmtgit/reusable_template/.github/workflows/reusable_testtemplate.yml@main
    with:
     file_path: DevOps_repo2_assessment_2/DevOps_repo2_assessment_2/src/dotnet-demoapp.csproj
