name: FindSecBugs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  BuildWithGitHubActions:

    runs-on: ubuntu-latest

    steps:
    
    - name: Download FindSecBugs   
      run: |
       wget -q -O findsecbugs-cli-1.12.0.zip https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.12.0/findsecbugs-cli-1.12.0.zip 
       unzip -qq findsecbugs-cli-1.12.0.zip
       chmod 755 findsecbugs.sh 
       chmod +x findsecbugs.sh
       ls -l
    
    - name: Run FindSecBugs
      run: ./findsecbugs.sh -progress -output findsecbugs-results.html -html target/*.jar

    - name: Upload FindSecBugs Report
      uses: actions/upload-artifact@v2
      with:
        name: findsecbugs-report
        path: findsecbugs-results.html
