name: DotNetBuild_With_MSBuild

on:
 workflow_call:
  inputs:
    file_path:
      required: false
      type: string

jobs:
  Demo_secrets:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.TOPSECRET }}
      run: |
       echo "My secret is"
       echo "$SUPER_SECRET"
