name: Secrets Handling

on:
 workflow_call:
  inputs:
    secret_repository:
     type: string
     required: true
     description: https://github.com/jpmtgit/DevSecOpsA2/settings/secrets/actions
    secret_repository_token:
     type: string
     required: true
     description: TOPSECRET

jobs:
  Demo_secrets:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.API_KEY }}
      run: |
       echo "My secret is"
       echo "$SUPER_SECRET"

