name: Secret Scanning

on:
 workflow_call:
  inputs:
    file_path:
      required: false
      type: string

jobs:
  Demo_secrets:
     runs-on: ubuntu-latest

     steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TOPSECRET }}
        run: |
         echo "Github"
         echo "$SUPER_SECRET"
