name: Reusable Secret Scan Template

on:
  push:
    branches: [main]  # Define the branch trigger as needed

jobs:
  demo_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Use reusable template
        run: |
          echo "Scanning for secrets..."
          echo "${{ secrets.TOPSECRET }}"
