name: Reusable Secret Scan Template
on: [workflow_call]

jobs:
  demo_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Use reusable template
        run: |
          echo "Scanning for secrets..."
          echo "${{ inputs.secret_var }}"
