name: Reusable Secret Scan Template
on: [workflow_call]  # Define the workflow_call trigger for reusability

jobs:
  demo_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Use reusable template
        run: |
          echo "Scanning for secrets..."
          echo "${{ secret.TOPSECRET }}"
